version: "3.8"

services:
  db:
    container_name: oncoped-db
    image: postgres:14
    env_file: .env
    ports:
      - "5455:5432"
    networks:
      - internal
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

  redis:
    container_name: oncoped-redis
    image: redis:alpine
    networks:
      - internal

  oncoped:
    container_name: oncoped-admin
    image: code4romania/oncologie-pediatrica:staging
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.centurylinklabs.watchtower.scope=oncologie
    env_file: .env
    networks:
      - internal
    ports:
      - "8071:8070"
    links:
      - "db:db"
    depends_on:
      - db
      - redis

  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --include-restarting --label-enable --scope oncologie --cleanup

networks:
  internal:
    driver: bridge

volumes:
  pgdata:
    name: oncoped-pgdata
